Update gh-pages-deploy.yaml

diff --git a/.github/workflows/gh-pages-deploy.yaml b/.github/workflows/gh-pages-deploy.yaml
--- a/.github/workflows/gh-pages-deploy.yaml
+++ b/.github/workflows/gh-pages-deploy.yaml
@@ -18,19 +18,26 @@ jobs:
 
       - name: Update README
         run: |
+          # Loop over all directories in the repository
           for dir in $(find . -type d); do
+          
+            # Skip irrelevant directories
             if [[ $dir =~ ^\.\/\.github ]] || [[ $dir =~ ^\.\/\.git ]]; then
               continue
             fi
-            if [ "$(find "$dir" -mindepth 1 -type d)" ]; then
-              echo "[LOG] Processing directory: $dir"
-              echo "## $dir" > $dir/README.md
-              echo "" >> $dir/README.md
-              echo "- [$(..)]($(..))" >> $dir/README.md
-              for subdir in $(find $dir -mindepth 1 -maxdepth 1 -type d); do
-                echo "- [$(basename $subdir)]($(basename $subdir))" >> $dir/README.md
-              done
+          
+            # Skip directories that do not contain subdirectories
+            if [ -z "$(find "$dir" -maxdepth 1 -type d)" ]; then
+              continue
             fi
+          
+            echo "[LOG] Processing directory: $dir"
+            echo "## $dir" > $dir/README.md || echo "Failed to create README in $dir"
+            echo "" >> $dir/README.md
+            echo "- [..]($(..))" >> $dir/README.md
+            for subdir in $(find $dir -maxdepth 1 -type d); do
+              echo "- [$(basename $subdir)]($(basename $subdir))" >> $dir/README.md
+            done
           done
         shell: bash
 
