Update gh-pages-deploy.yaml

diff --git a/.github/workflows/gh-pages-deploy.yaml b/.github/workflows/gh-pages-deploy.yaml
--- a/.github/workflows/gh-pages-deploy.yaml
+++ b/.github/workflows/gh-pages-deploy.yaml
@@ -26,7 +26,7 @@ jobs:
             echo "## [$(basename $dir)]($dir)" > $dir/README.md || echo "Failed to create README in $dir"
             echo "" >> $dir/README.md
             for subdir in $(find $dir -maxdepth 1 -mindepth 1 -type d); do
-              echo "- [$(basename $subdir)]($subdir)" >> $dir/README.md || echo "Failed to update README in $dir"
+              echo "- [$(basename $subdir)]($(basename $subdir))" >> $dir/README.md || echo "Failed to update README in $dir"
             done
           done
         shell: bash
