Update gh-pages-deploy.yaml

diff --git a/.github/workflows/gh-pages-deploy.yaml b/.github/workflows/gh-pages-deploy.yaml
--- a/.github/workflows/gh-pages-deploy.yaml
+++ b/.github/workflows/gh-pages-deploy.yaml
@@ -19,15 +19,14 @@ jobs:
       - name: Update README
         run: |
           for dir in $(find . -maxdepth 2 -type d); do
-            if [ $dir == "./.github" ] || [ $dir == "./.github/workflows" ]; then
+            if [ $dir == "./.github" ] || [ $dir == "./.git" ]; then
               continue
             fi
             echo "Processing directory: $dir"
-            echo "# [- $(basename $dir)]($dir)" > $dir/README.md || echo "Failed to create README in $dir"
+            echo "## [$(basename $dir)](basename $dir)" > $dir/README.md || echo "Failed to create README in $dir"
             echo "" >> $dir/README.md
-            echo "## [- $(basename $dir)]($dir)" >> $dir/README.md
-            for subdir in $(find $dir -maxdepth 1 -mindepth 1 -type d); do
-              echo "- [$(basename $subdir)]($subdir)" >> $dir/README.md || echo "Failed to update README in $dir"
+            for subdir in $(find $dir -maxdepth 1 -mindepth 1 -type d); doa
+              echo "- [$(basename $subdir)]($subdir)" >> $dir/README.md || echo "Failed to updte README in $dir"
             done
           done
         shell: bash
