Update gh-pages-deploy.yaml

diff --git a/.github/workflows/gh-pages-deploy.yaml b/.github/workflows/gh-pages-deploy.yaml
--- a/.github/workflows/gh-pages-deploy.yaml
+++ b/.github/workflows/gh-pages-deploy.yaml
@@ -26,27 +26,23 @@ jobs:
               continue
             fi
           
-            # Skip directories that do not contain subdirectories
             if [ -z "$(find "$dir" -mindepth 1 -maxdepth 1 -type d)" ]; then
+              echo "[LOG] UPDATE README.md at $dir: link of source code"
               echo "" >> $dir/README.md
               echo "## 소스 코드" >> $dir/README.md
               for file in $(find $dir -type f); do
-                if [[ $file =~ ^\.\/README\.md ]]; then
-                  continue
+                if [[ $(basename $file) != "README.md" ]]; then
+                  echo "- [$(basename $file)]($(basename $file))" >> $dir/README.md
                 fi
-                echo "- [$(basename $file)]($(basename $file))" >> $dir/README.md
               done
-              continue
+            else
+              echo "[LOG] CREATE README.md at $dir: index of sub-directories"
+              echo "## $dir" > $dir/README.md || echo "Failed to create README in $dir"
+              echo "" >> $dir/README.md
+              for subdir in $(find $dir -mindepth 1 -maxdepth 1 -type d); do
+                echo "- [$(basename $subdir)]($(basename $subdir))" >> $dir/README.md
+              done
             fi
-          
-            echo "[LOG] Processing directory: $dir"
-          
-            echo "## $dir" > $dir/README.md || echo "Failed to create README in $dir"
-            echo "" >> $dir/README.md
-        
-            for subdir in $(find $dir -mindepth 1 -maxdepth 1 -type d); do
-              echo "- [$(basename $subdir)]($(basename $subdir))" >> $dir/README.md
-            done
           
           done
         shell: bash
