Update gh-pages-deploy.yaml

diff --git a/.github/workflows/gh-pages-deploy.yaml b/.github/workflows/gh-pages-deploy.yaml
--- a/.github/workflows/gh-pages-deploy.yaml
+++ b/.github/workflows/gh-pages-deploy.yaml
@@ -16,13 +16,23 @@ jobs:
       - name: Check out
         uses: actions/checkout@v4
 
+      - name: Update root README
+        run: |
+          for subdir in $(find . -mindepth 1 -maxdepth 1 -type d); do
+            if [[ $dir =~ ^\.\/\.github* ]] || [[ $dir =~ ^\.\/\.git* ]]; then
+              continue
+            fi
+            echo "- [$(basename $subdir)]($(basename $subdir))" >> $dir/README.md
+          done
+        shell: bash
+
       - name: Update README
         run: |
           # Loop over all directories in the repository
           for dir in $(find . -type d); do
           
             # Skip irrelevant directories
-            if [[ $dir =~ ^\.\/\.github* ]] || [[ $dir =~ ^\.\/\.git* ]]; then
+            if [[ $dir == . ]] ||[[ $dir =~ ^\.\/\.github* ]] || [[ $dir =~ ^\.\/\.git* ]]; then
               continue
             fi
           
@@ -33,16 +43,13 @@ jobs:
           
             echo "[LOG] Processing directory: $dir"
           
-            # If the directory is not the root directory, add the title and the link to the parent directory
-            if [[ $dir != "." ]]; then
-              echo "## $dir" > $dir/README.md || echo "Failed to create README in $dir"
-              echo "" >> $dir/README.md
-              echo "- [./..]($(dirname $dir))" >> $dir/README.md
-            fi
-          
+            echo "## $dir" > $dir/README.md || echo "Failed to create README in $dir"
+            echo "" >> $dir/README.md
+            echo "- [./..]($(dirname $dir))" >> $dir/README.md
             for subdir in $(find $dir -mindepth 1 -maxdepth 1 -type d); do
               echo "- [$(basename $subdir)]($(basename $subdir))" >> $dir/README.md
             done
+          
           done
         shell: bash
 
